name: Build Docker Image
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up buildx action
        uses: docker/setup-buildx-action@v3

      - name: Build docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: CalendarView/CalendarView.Web/Dockerfile
